server:
  port: 8023
  # 应用名称 （nacos会将该名称当做服务名称）
spring:
  application:
    name: product-service
  cloud:
    nacos:
      server-addr: 8.134.165.135:8847
      discovery:
        username: nacos
        password: nacos
        namespace: public